# Generated by Django 2.2.14 on 2020-07-19 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VoucherConfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Отметьте, если объект должен быть активным', verbose_name='Активен?')),
                ('name', models.CharField(help_text='Введите название ваучера', max_length=256, verbose_name='Название ваучера')),
                ('description', models.CharField(blank=True, default='', help_text='Введите опсание ваучера', max_length=512, verbose_name='Описание ваучера')),
                ('type', models.CharField(choices=[('min_purchase_amount', 'Минимальное кол-во покупок'), ('for_registration', 'За регестрацию'), ('for_all_users', 'Для всех пользователей')], default='min_purchase_amount', help_text='Выберете тип ваучера (в каких случаях ользователи будут получать ваучеры)', max_length=32, verbose_name='Тип ваучера')),
                ('discount', models.CharField(default='fixed', help_text='Выберете тип скидки', max_length=32, verbose_name='Выберете')),
                ('amount', models.DecimalField(decimal_places=2, help_text='Выставите значение скидки (процент либо фиксированное значение)', max_digits=8, verbose_name='Значение')),
            ],
            options={
                'verbose_name': 'Шаблон ваучера',
                'verbose_name_plural': 'Шаблоны ваучеров',
            },
        ),
    ]
