# Generated by Django 2.2.14 on 2020-07-29 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voucher', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='voucherconfig',
            name='purchase_count',
            field=models.PositiveIntegerField(blank=True, help_text='Set minimum purchase amount for receiving voucher', null=True, verbose_name='Purchase count'),
        ),
    ]
