# Generated by Django 2.2.14 on 2020-07-19 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voucher', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='voucherconfig',
            name='duration',
            field=models.DurationField(blank=True, help_text='Выставите, сколько ваучер будет доступен после получения (оставьте пустым для того, что бы ваучер действовал всегда )', null=True, verbose_name='Длительность действия'),
        ),
        migrations.AlterField(
            model_name='voucherconfig',
            name='discount',
            field=models.CharField(choices=[('fixed', 'Фиксированная скидка'), ('percentage', 'Процентная скидка'), ('free_item', 'Бесплатный продукт')], default='fixed', help_text='Выберете тип скидки', max_length=32, verbose_name='Выберете тип скидки'),
        ),
    ]
