# Generated by Django 2.2.14 on 2020-08-19 13:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0004_auto_20200811_1830'),
        ('voucher', '0002_voucherconfig_purchase_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='voucherconfig',
            name='free_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='menu.Product'),
        ),
        migrations.AlterField(
            model_name='voucherconfig',
            name='amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Set discount amount', max_digits=8, null=True, verbose_name='Amount'),
        ),
    ]
