# Generated by Django 2.2.14 on 2020-07-24 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voucher', '0003_voucher'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voucher',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='дата содания'),
        ),
    ]
