# Generated by Django 2.2.14 on 2020-07-24 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voucher', '0004_auto_20200724_1613'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voucherconfig',
            name='duration',
            field=models.PositiveIntegerField(blank=True, help_text='Выставите, сколько ваучер будет доступен после получения (оставьте пустым для того, что бы ваучер действовал всегда )', null=True, verbose_name='Длительность действия'),
        ),
    ]
