# Generated by Django 2.2.14 on 2020-07-26 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voucher', '0005_auto_20200724_1933'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='voucherconfig',
            options={'verbose_name': 'Voucher discount', 'verbose_name_plural': 'Voucher discount'},
        ),
        migrations.AlterField(
            model_name='voucher',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Creation date'),
        ),
        migrations.AlterField(
            model_name='voucher',
            name='expiration_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Expiration date'),
        ),
        migrations.AlterField(
            model_name='voucher',
            name='is_scanned',
            field=models.BooleanField(default=False, verbose_name='Is scanned?'),
        ),
        migrations.AlterField(
            model_name='voucherconfig',
            name='amount',
            field=models.DecimalField(decimal_places=2, help_text='Set discount amount', max_digits=8, verbose_name='Amount'),
        ),
        migrations.AlterField(
            model_name='voucherconfig',
            name='description',
            field=models.CharField(blank=True, default='', help_text='Enter voucher description', max_length=512, verbose_name='Voucher description'),
        ),
        migrations.AlterField(
            model_name='voucherconfig',
            name='discount',
            field=models.CharField(choices=[('fixed', 'Fixed discount'), ('percentage', 'Percentage dicount'), ('free_item', 'Free product')], default='fixed', help_text='Select discount type', max_length=32, verbose_name='Discount type'),
        ),
        migrations.AlterField(
            model_name='voucherconfig',
            name='duration',
            field=models.PositiveIntegerField(blank=True, help_text='Set how much days will voucher be available after creation', null=True, verbose_name='Voucher duration'),
        ),
        migrations.AlterField(
            model_name='voucherconfig',
            name='name',
            field=models.CharField(help_text='Enter voucher name', max_length=256, verbose_name='Voucher name'),
        ),
        migrations.AlterField(
            model_name='voucherconfig',
            name='type',
            field=models.CharField(choices=[('min_purchase_amount', 'Minimum purchase amount'), ('for_registration', 'For registration'), ('for_all_users', 'For all users')], default='min_purchase_amount', help_text='Select voucher type (in which case user receive voucher)', max_length=32, verbose_name='Voucher type'),
        ),
    ]
