# Generated by Django 2.2.14 on 2020-07-26 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voucher', '0006_auto_20200726_1627'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voucher',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True, help_text='Designate, if object is active', verbose_name='Is active?'),
        ),
        migrations.AlterField(
            model_name='voucherconfig',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True, help_text='Designate, if object is active', verbose_name='Is active?'),
        ),
    ]
