# Generated by Django 2.2.14 on 2020-08-06 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_post_short_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='short_description',
        ),
        migrations.AlterField(
            model_name='post',
            name='content',
            field=models.TextField(verbose_name='Post content'),
        ),
    ]
