# Generated by Django 2.2.14 on 2020-08-06 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0003_auto_20200806_2029'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostConfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('show_post_section', models.BooleanField(default=True, verbose_name='Show post section in app?')),
                ('max_post_amount', models.PositiveSmallIntegerField(default=5, help_text="Set how much post to show in mobile app. Rest of the post will be visible after clicking 'more' button", verbose_name='How much post to show in mobile app?')),
            ],
            options={
                'verbose_name': 'Posts config',
            },
        ),
    ]
