# Generated by Django 2.2.14 on 2020-07-24 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RestaurantConfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter restaurant name', max_length=512, verbose_name='Name')),
                ('email', models.EmailField(blank=True, help_text='Enter restaurant email address', max_length=254, null=True, verbose_name='Email')),
                ('website', models.URLField(blank=True, help_text='Enter restaurant website', null=True, verbose_name='Website')),
                ('phone', models.CharField(blank=True, help_text='Enter restaurant phone number', max_length=16, null=True, verbose_name='Phone number')),
                ('instagram_link', models.CharField(blank=True, help_text='Enter Instagram link', max_length=256, null=True, verbose_name='Instagram link')),
                ('facebook', models.CharField(blank=True, help_text='Enter Facebook link', max_length=256, null=True, verbose_name='Facebook link')),
                ('logo', models.ImageField(blank=True, help_text='Add restaurant logo to display it in the app', null=True, upload_to='restaurant', verbose_name='Restaurant logo')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='WorkHours',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('begin', models.TimeField(verbose_name='Начало')),
                ('end', models.TimeField(verbose_name='Конец')),
            ],
            options={
                'verbose_name': 'Рабочие время',
            },
        ),
        migrations.CreateModel(
            name='WeekDay',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.PositiveSmallIntegerField(choices=[(1, 'Monday'), (2, 'Tuesday'), (3, 'Wednesday'), (4, 'Thursday'), (5, 'Friday'), (6, 'Saturday'), (7, 'Sunday')], unique=True)),
                ('duration', models.ManyToManyField(help_text='Working hours', to='config.WorkHours', verbose_name='Duration')),
            ],
            options={
                'verbose_name': 'Week day',
                'verbose_name_plural': 'Week days',
            },
        ),
        migrations.CreateModel(
            name='RestaurantBranch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Отметьте, если объект должен быть активным', verbose_name='Активен?')),
                ('branch_name', models.CharField(help_text='Enter branch name', max_length=512, verbose_name='Branch name')),
                ('branch_phone', models.CharField(blank=True, help_text='Enter restaurant phone number', max_length=16, null=True, verbose_name='Phone number')),
                ('address', models.CharField(help_text='Enter Branch address', max_length=512, verbose_name='Branch address')),
                ('google_maps_iframe', models.TextField(blank=True, help_text="Click 'Share or embed map', then click 'Embed map' and copy-paste code there", verbose_name='Google Maps embedded code')),
                ('image', models.ImageField(blank=True, help_text='Add branch image to display it in the app', null=True, upload_to='restaurant/branches', verbose_name='Branch image')),
                ('short_description', models.CharField(blank=True, help_text='Enter short description of branch', max_length=512, null=True, verbose_name='Short description')),
                ('working_days', models.ManyToManyField(blank=True, help_text='Specify days in which branch will work', to='config.WeekDay', verbose_name='Working hours during week')),
            ],
            options={
                'verbose_name': 'Restaurant branch',
                'verbose_name_plural': 'Restaurant branches',
            },
        ),
    ]
