# Generated by Django 2.2.14 on 2020-07-25 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurantbranch',
            name='image',
            field=models.ImageField(blank=True, help_text='Add branch image to display it in the app', null=True, upload_to='branch_images', verbose_name='Branch image'),
        ),
    ]
