# Generated by Django 2.2.14 on 2020-07-27 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='workhours',
            options={'verbose_name': 'Work Hours'},
        ),
        migrations.AlterField(
            model_name='restaurantbranch',
            name='image',
            field=models.ImageField(blank=True, help_text='Add branch image to display it in the app', null=True, upload_to='branch_images', verbose_name='Branch image'),
        ),
        migrations.AlterField(
            model_name='restaurantbranch',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True, help_text='Designate, if object is active', verbose_name='Is active?'),
        ),
        migrations.AlterField(
            model_name='workhours',
            name='begin',
            field=models.TimeField(verbose_name='Start'),
        ),
        migrations.AlterField(
            model_name='workhours',
            name='end',
            field=models.TimeField(verbose_name='End'),
        ),
    ]
