# Generated by Django 2.2.14 on 2020-09-07 19:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0002_auto_20200727_2236'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restaurantbranch',
            name='working_days',
        ),
        migrations.AddField(
            model_name='restaurantbranch',
            name='weekday_working_hours',
            field=models.ForeignKey(help_text='Set working hours during weekdays', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='weekday_working_hours', to='config.WorkHours'),
        ),
        migrations.AddField(
            model_name='restaurantbranch',
            name='weekend_working_hours',
            field=models.ForeignKey(help_text='Set working hours during weekends', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='weekend_working_hours', to='config.WorkHours'),
        ),
    ]
