# Generated by Django 2.2.14 on 2020-09-17 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0003_auto_20200907_1906'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='restaurantconfig',
            options={'verbose_name': 'Restaurant config'},
        ),
        migrations.AddField(
            model_name='restaurantbranch',
            name='lat',
            field=models.DecimalField(decimal_places=6, help_text='Enter latitude of branch', max_digits=10, null=True, verbose_name='Latitude'),
        ),
        migrations.AddField(
            model_name='restaurantbranch',
            name='lon',
            field=models.DecimalField(decimal_places=6, help_text='Enter longitude of branch', max_digits=10, null=True, verbose_name='Longitude'),
        ),
    ]
