# Generated by Django 2.2.14 on 2020-09-25 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0004_auto_20200917_1900'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppMetadataConfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('terms_and_conditions', models.TextField(help_text='Enter app terms and Conditions', verbose_name='Terms and Conditions')),
                ('android_download_link', models.URLField(verbose_name='Android app download link')),
                ('ios_download_link', models.URLField(verbose_name='IOS app download link')),
            ],
            options={
                'verbose_name': 'App metadata config',
            },
        ),
    ]
