# Generated by Django 2.2.14 on 2020-09-29 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0005_appmetadataconfig'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='workhours',
            options={'verbose_name': 'Work Hour'},
        ),
        migrations.AddField(
            model_name='appmetadataconfig',
            name='privacy_policy',
            field=models.TextField(default='', help_text='Enter app Privacy Policy', verbose_name='Privacy Policy'),
            preserve_default=False,
        ),
    ]
