# Generated by Django 2.2.14 on 2020-08-07 15:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('voucher', '0002_voucherconfig_purchase_count'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScanLogEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Creation date')),
                ('type', models.CharField(choices=[('voucher', 'voucher'), ('user', 'User')], max_length=7)),
                ('status', models.BooleanField(default=False, verbose_name='Did QR code was successfully scanned?')),
                ('error_message', models.CharField(blank=True, max_length=512, null=True, verbose_name='Error message')),
                ('initiator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scan_logs', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('voucher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='voucher.Voucher')),
            ],
            options={
                'verbose_name': 'Scan log',
                'verbose_name_plural': 'Scan logs',
            },
        ),
    ]
