# Generated by Django 2.2.14 on 2020-08-07 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scanlogentry',
            name='status',
            field=models.BooleanField(default=False, verbose_name='Successfully scanned?'),
        ),
    ]
