# Generated by Django 2.2.14 on 2020-09-10 19:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0002_auto_20200807_1605'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='scanlogentry',
            options={'ordering': ['-created'], 'verbose_name': 'Scan log', 'verbose_name_plural': 'Scan logs'},
        ),
    ]
