# Generated by Django 2.2.14 on 2020-11-29 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0003_auto_20200910_1938'),
    ]

    operations = [
        migrations.AddField(
            model_name='scanlogentry',
            name='is_voucher_received',
            field=models.BooleanField(default=False, verbose_name='Is voucher received?'),
        ),
    ]
