# Generated by Django 2.2.14 on 2020-11-29 19:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0004_scanlogentry_is_voucher_received'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scanlogentry',
            name='is_voucher_received',
        ),
    ]
