# Generated by Django 2.2.14 on 2020-07-29 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='current_purchase_count',
            field=models.PositiveIntegerField(default=0, help_text='Count of current user purchase', verbose_name='Current user purchase'),
        ),
    ]
