# Generated by Django 2.2.14 on 2020-09-02 21:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_user_firebase_uid'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
            ],
        ),
    ]
