# Generated by Django 2.2.14 on 2020-08-08 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_auto_20200805_1629'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(upload_to='products/images'),
        ),
        migrations.DeleteModel(
            name='ProductImage',
        ),
    ]
