# Generated by Django 2.2.14 on 2020-10-28 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0004_auto_20200811_1830'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productcategory',
            options={'ordering': ['order'], 'verbose_name': 'Category', 'verbose_name_plural': 'Categories'},
        ),
        migrations.AddField(
            model_name='productcategory',
            name='order',
            field=models.PositiveIntegerField(default=0, help_text='Specify order in which categories will be displayed on frontend', verbose_name='Order'),
        ),
    ]
