# Generated by Django 2.2.14 on 2020-07-27 22:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('voucher', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VoucherQRCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qr_code', models.ImageField(blank=True, null=True, upload_to='vouchers/qr_codes', verbose_name='QR Code')),
                ('voucher', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='qr_code', to='voucher.Voucher', verbose_name='Voucher')),
            ],
            options={
                'verbose_name': 'Voucher QR code',
                'verbose_name_plural': 'Voucher QR code',
            },
        ),
        migrations.CreateModel(
            name='UserQRCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qr_code', models.ImageField(blank=True, null=True, upload_to='qr_codes', verbose_name='QR code')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='qr_code', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'User QR code',
                'verbose_name_plural': 'User QR codes',
            },
        ),
    ]
