# Generated by Django 2.2.14 on 2020-07-22 16:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('voucher', '0003_voucher'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VoucherQRCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qr_code', models.ImageField(blank=True, null=True, upload_to='qr_codes', verbose_name='QR код')),
                ('voucher', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='qr_code', to='voucher.Voucher', verbose_name='Ваучер')),
            ],
            options={
                'verbose_name': 'QR код ваучера',
                'verbose_name_plural': 'QR коды ваучеров',
            },
        ),
        migrations.CreateModel(
            name='UserQRCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qr_code', models.ImageField(blank=True, null=True, upload_to='qr_codes', verbose_name='QR код')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='qr_code', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'QR код пользователя',
                'verbose_name_plural': 'QR коды пользователей',
            },
        ),
    ]
