# Generated by Django 2.2.14 on 2020-07-24 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qr_code', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voucherqrcode',
            name='qr_code',
            field=models.ImageField(blank=True, null=True, upload_to='vouchers/qr_codes', verbose_name='QR код'),
        ),
    ]
