# Generated by Django 2.2.14 on 2020-07-26 16:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('qr_code', '0002_auto_20200724_1940'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userqrcode',
            options={'verbose_name': 'User QR code', 'verbose_name_plural': 'User QR codes'},
        ),
        migrations.AlterModelOptions(
            name='voucherqrcode',
            options={'verbose_name': 'Voucher QR code', 'verbose_name_plural': 'Voucher QR code'},
        ),
        migrations.AlterField(
            model_name='userqrcode',
            name='qr_code',
            field=models.ImageField(blank=True, null=True, upload_to='qr_codes', verbose_name='QR code'),
        ),
        migrations.AlterField(
            model_name='userqrcode',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='qr_code', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AlterField(
            model_name='voucherqrcode',
            name='voucher',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='qr_code', to='voucher.Voucher', verbose_name='Voucher'),
        ),
    ]
